version: "0.2"
words:
  - actix
  - clippy
  - distroless
  - dotenv
  - dotenvy
  - goose
  - hatch
  - loadtest
  - nocapture
  - postgres
  - seeder
  - serde
  - sqlx
  - thiserror
  - tokio
  - utoipa
